name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install libs
        run: |
          sudo apt-get install make
          sudo apt-get install gcc
          sudo apt-get install mingw-w64
          sudo apt-get install libomp-12-dev
      #      - name: configure
      #        run: ./configure
      - name: make
        run: make
      #    - name: make check
      #      run: make check
#      - name: make distcheck
#        run: make distcheck

